sudo: false
dist: trusty

# safelist, worked on develop, master and tag branch
branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+\.\d+$/

language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - [skip travis] README
  - [skip travis] CHANGELOG
  - |
    #check if test task need to be run
    IS_RUN_TESTS=true
    #check if build task need to be run(normally, true if push a tag, or a pr to develop)
    is_RUN_BUILD=true
    # if merge to master from develop, no need to run build task
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST_BRANCH" == "develop" ]]; then
        IS_RUN_TESTS=false
    fi
  - gradle wrapper

script:
  -|
    if [ "$is_RUN_BUILD" = "true" ] ; then
        chmod +x ci/script/build-ci.sh
        ci/script/build-ci.sh
        if [ "$IS_RUN_TESTS" = "true" ] ; then
            travis_wait 30 ./gradlew check
            ./gradlew jacocoTestReport
        fi
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
    provider: releases
    api_key: $GIT_REPO_TOKEN
    file_glob: true
    file: dist/app/weidentity-java-sdk*.jar
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
